'use strict'

// Designer Add Layer labels, independent of project-specific layer names.
const labels = Object.freeze({
  TwoPoint5DModule: '2.5D',
  AudioModule: 'Audio',
  DepthVideoModule: 'Depth Video',
  RenderStreamModule: 'Render Stream',
  RenderStreamLocalModule: 'Render Stream Local',
  StageRenderModule: 'Stage Render',
  VariableVideoModule: 'Video',
  VideoTriggerModule: 'Video Trigger',
  VirtualLineupModule: 'Virtual Lineup',
  WebModule: 'Web',
  CameraControlModule: 'Camera Control',
  CameraCutControl: 'Camera Cut Control',
  ControlModule: 'Control',
  DmxControlModule: 'Dmx Lights Control',
  DmxShareModule: 'Dmx Share',
  ExpressionVariablesModule: 'Expression Variables',
  HttpControlModule: 'Http Control',
  IndirectionControl: 'Indirection Control',
  MDCModule: 'MDC',
  MtcModule: 'MTC',
  MasterModule: 'Master Brightness',
  DVIMatrixControlModule: 'Matrix Control',
  MidiNoteModule: 'Midi Note',
  OpenModule: 'Open',
  OscControlModule: 'Osc Control',
  PlayModeModule: 'Play Mode',
  ProjectorControlModule: 'Projector Control',
  TargetObjectModule: 'Target Object',
  IgnoreTimecodeModule: 'Timecode Mode',
  TrackJumpModule: 'Track Jump',
  TransportBrightnessLocalModule: 'Transport Brightness Local',
  TransportControlModule: 'Transport Control',
  TransportVolumeLocalModule: 'Transport Volume Local',
  BlurModule: 'Blur',
  CDLModule: 'CDL',
  ChannelRouterModule: 'Channel Router',
  ColourAdjustModule: 'Colour Adjust',
  ComposeModule: 'Compose',
  EdgeFilterModule: 'Edge Filter',
  FadeModule: 'Fade',
  FilmicGrainModule: 'Filmic Grain',
  KaleidoscopeModule: 'Kaleidoscope',
  LutModule: 'Lut',
  MotionBlurModule: 'Motion Blur',
  NoiseModule: 'Noise',
  OCIOModule: 'OCIO',
  PixelMapModule: 'Pixel Map',
  PixelateModule: 'Pixelate',
  ScrollModule: 'Scroll',
  SpinBitmap: 'Spin Bitmap',
  TriggerModule: 'Trigger',
  UVLookupModule: 'UVLookup',
  VariableVideoTransitionModule: 'Video Transition',
  BugsModule: 'Bugs',
  ChevronModule: 'Chevron',
  ColourModule: 'Colour',
  GradientModule: 'Gradient',
  NotchModule: 'Notch',
  RGBColourModule: 'RGBColour',
  RadarModule: 'Radar',
  TimecodeReadoutModule: 'Readout',
  ScanModule: 'Scan',
  StrobeModule: 'Strobe',
  PongModule: 'Tennis',
  TestPatternModule: 'Test Pattern',
  TextModule: 'Text',
  TrackingMarkerModule: 'Tracking Marker',
  BitmapModule: 'Bitmap',
  VideoModule: 'Legacy Video',
  VideoTransitionModule: 'Legacy Video Transition',
  AnimateCamera: 'Animate Camera Control',
  AnimateCamera2: 'Animate Camera Preset',
  ScreenPositionModule: 'Animate Object Preset',
  SceneAnimationModule: 'Scene Animation',
  TargetModule: 'Target Control',
  Target2Module: 'Target Preset',
})

function layerTypeLabel(type = '') {
  return labels[type] || type.replace(/Module$/, '').replace(/([a-z0-9])([A-Z])/g, '$1 $2')
}

module.exports = { layerTypeLabel }
